version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: git submodule update --init
before_build:
- cmd: nuget restore Razor.sln
build:
  project: Razor.sln
  verbosity: minimal
test: off
artifacts:
- path: bin\x64\Release
  name: RazorSE-dev
deploy:
- provider: GitHub
  release: RazorSE-dev
  description: Auto-build by AppVeyor\n\nThis is built automatically after each commit to master, so it may contain bugs and/or unfinished features. Use at your own risk.\n\nOfficial releases will be listed here and given proper version numbers with release notes.
  auth_token:
    secure: M4cbbL2lbfYZDL5oMaOtZVTchZ1cWi1DN2nCuwhelFwgYEKwIG2gd+KVyw4LzCD1
  prerelease: true
  force_update: true
skip_commits:
  message: /\[chore\]/
  files:
    - help/
    - docs/
    - '**/*.md'
    - '**/*.ps1'
    - '**/*.yml'